auth:
  algorithm: HS256
  secret_key: "passlib_generated_key"

database:

  url: "sqlite:////home/username/rubato.db" #mysql:// using schema in sqlachemy
  # username: 
  # password: 

server:

  backend:
    address: "0.0.0.0"
    port: 6660

  frontend:
    address: "0.0.0.0"
    port: 7770
